### PR TITLE
Add gas-same-gpu annotation support and minor fixes

### PR DESCRIPTION
**Pull request by byako**
This PR contains GPU-aware-scheduler (GAS) changes:

- new feature: `gas-same-gpu` annotation on Pod ensures that specified containers within Pod have the same GPU device allocated by GAS
 - minor fixes to the GAS code, documentation

### CODE REVIEW

**Comment by byako** [comment]
Rebased.

**Review by madalazar — APPROVED** [review]
LGTM!

**Review by uniemimu — APPROVED** [review]
Partially my own doing, so I'm obviously ok with this. But I'd like to give Denisio a chance to review also.

**Review by togashidm — APPROVED** [review]
Apologies for the delay. Just back from a break :)  
I have looked at the PR, you may consider removing .golangci.yml file from the gas folder.
All the rest looks good to me!

**Comment by byako** [comment]
Let's keep it, we call golangci-lint in GAS subdir Makefile, and golangci-lint does not look for config file in parent folder, only current folder and home folder, so removing it would break linting GAS code separately. We can sync GAS .golangci.yml and parent dir PAS .golangci.yml in next release.

**Comment by togashidm** [comment]
right then. Thank you for the PR!

**Pull request merged**
